DROP DATABASE IF EXISTS user_db;
CREATE DATABASE user_db;

DROP DATABASE IF EXISTS friends_db;
CREATE DATABASE friends_db;

DROP DATABASE IF EXISTS ratings_db;
CREATE DATABASE ratings_db;

DROP DATABASE IF EXISTS movies_db;
CREATE DATABASE movies_db;